config/routes.rb
RecipppeApi::Application.routes.draw do

  get '/auth/facebook/callback', to: 'users#create'
  get '/signout', to: 'sessions#destroy', as: :signout
  root to: 'users#new'

  resources :recipes, only: [:index, :create, :edit, :destroy]

  namespace :api do
    resources :categories, only: [:index]
    resources :recipes, only: [:show, :create, :update, :destroy] do
      post :cover, on: :member
      resources :recipe_images, only: [:index, :create, :destroy]
    end
  end

end

app/models/category.rb
class Category
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :slug, type: String
  
  has_many :recipes
  before_validation :generate_slug
  validates :name, :slug, presence: true
  
protected
  
  def generate_slug
    self.slug ||= name.parameterize if name.present?
  end
  
end

app/models/line_item.rb
class LineItem
  include Mongoid::Document

  ITEM_TYPES = ['list', 'single', 'image']

  field :item_type, type: String, default: 'list'
  field :tag, type: String
  field :content, type: String
  field :position, type: Integer, default: 100
  field :name, type: String
  field :_id, type: String, default: -> { name }

  validates :item_type, :name, :tag, presence: true
  validates :item_type, inclusion: { in: ITEM_TYPES }
  default_scope -> { order_by([:position]) }
  embedded_in :recipe

end

app/models/recipe.rb
class Recipe

  require 'base62'
  include Mongoid::Document
  include Mongoid::Timestamps

  auto_increment :sequence, seed: 100
  field :user_id, type: String
  field :category_id, type: String
  field :name, type: String
  field :shortened_url, type: String
  field :servings, type: Integer, default: 2
  field :preparation_time, type: Integer, default: 30
  field :published, type: Boolean, default: false

  mount_uploader :cover_image, CoverImageUploader

  belongs_to :user
  belongs_to :category
  embeds_many :line_items
  embeds_many :recipe_images
  accepts_nested_attributes_for :line_items, allow_destroy: true

  validates :user, :name, presence: true
  validates :category, :shortened_url, :servings, :preparation_time, presence: true, on: :update

  before_validation :set_default_category
  after_create :generate_shortened_url, :create_default_line_item

  def cover_image_large_url
    cover_image.url(:large)
  end

  def update(attrs)
    line_items_attributes = attrs.delete(:line_items_attributes)
    super(attrs)
    update_line_items(line_items_attributes) if line_items_attributes
  end

  # FIXME: Spec will not pass since we do not expect paramenters
  # contain an array instead of a simple hash
  # That's why we are using a map(:&last) here
  def update_line_items(line_items_attributes)
    line_items_attributes.map(&:last).each do |attrs|
      if attrs.has_key?(:_destroy)
        destroy_line_item(attrs[:name])
      else
        find_or_create_line_item(attrs)
      end
    end
  end

protected

  def set_default_category
    self.category_id ||= Category.first.id
  end

  def create_default_line_item
    line_items.create({
      item_type: 'single',
      tag: 'h2',
      content: '',
      name: SecureRandom.hex(2)
    })
  end

  def generate_shortened_url
    update_attribute(:shortened_url, self.sequence.base62_encode)
  end

  def find_or_create_line_item(attrs)
    line_item = line_items.where(name: attrs[:name]).first_or_initialize
    line_item.assign_attributes(attrs) and line_item.save
    line_item
  end

  def destroy_line_item(name)
    line_items.where(name: name).try(:first).try(:destroy)
  end

end

app/models/recipe_image.rb
class RecipeImage

  include Mongoid::Document
  include Mongoid::Timestamps

  embedded_in :recipe
  mount_uploader :image, RecipeImageUploader
end

app/models/user.rb
class User

  include Mongoid::Document
  include Mongoid::Timestamps

  field :uid, type: String
  field :username, type: String
  field :token, type: String
  field :email, type: String
  field :name, type: String
  field :profile_image, type: String
  field :approved, type: Boolean, default: false
  field :location, type: String
  field :optin, type: Boolean, default: true
  field :confirmation_token, type: String
  field :confirmed_at, type: DateTime
  field :utm_source, type: String
  field :utm_campaign, type: String
  field :utm_medium, type: String
  field :utm_content, type: String
  field :utm_term, type: String

  validates :uid, :username, :token, :email, :name, :profile_image, presence: true
  validates :uid, :username, :token, :email, uniqueness: true

  has_many :recipes

  def self.from_omniauth(auth)
    find_or_create_by!(uid: auth['uid']) do |u|
      u.username = auth['extra']['raw_info']['username']
      u.token = auth['credentials']['token']
      u.email = auth['info']['email']
      u.name = auth['info']['name']
      u.profile_image = auth['info']['image']
      u.location = auth['info']['location']
    end rescue User.new
  end

  def large_profile_image
    "#{profile_image}?type=large"
  end

end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController

  respond_to :json
  
  def index
    respond_with Category.all
  end

end

app/controllers/api/recipe_images_controller.rb
class Api::RecipeImagesController < ApplicationController

  def index
  end

  def create
    respond_to do |format|
      format.json do
        render json: upload_service.upload_image
      end
    end
  end

  def destroy
  end

  private

  def recipe
    @recipe ||= Recipe.find(params[:recipe_id])
  end

  def image_param
    params[:image].first
  end

  def upload_service
    RecipeImagesUploadService.new(recipe, image_param)
  end
end

app/controllers/api/recipes_controller.rb
class Api::RecipesController < ApplicationController

  before_action :authenticate_user!, :load_recipe
  respond_to :json

  def show
    respond_with @recipe.to_json(include: [:line_items], methods: [:cover_image_large_url])
  end

  def update
    @recipe.update(recipe_params)
    respond_with @recipe
  end

  def cover
    @recipe.update({ cover_image: params[:cover_image][0] })
    respond_to do |format|
      format.json {
        @recipe.reload
        render json: @recipe.to_json(methods: [:cover_image_large_url])
      }
    end
  end

protected

  def load_recipe
    @recipe = current_user.recipes.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:published, :name, :servings, :preparation_time, :category_id, line_items_attributes: [:item_type, :name, :tag, :content, :position, :_destroy])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to root_path unless current_user
  end

  def sign_in(user)
    cookies[:token] = user.id
  end

  def sign_out
    cookies.delete :token
  end

  def current_user
    @current_user ||= User.find(cookies[:token]) if cookies[:token]
  rescue
    nil
  end
  helper_method :current_user

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!
  before_action :load_recipe, only: [:edit, :show, :destroy]

  def index
    @recipes = current_user.recipes.order(created_at: :desc)
  end

  def create
    @recipe = current_user.recipes.find_or_create_by(recipe_params)

    redirect_to after_create_path
  end

  def edit; end
  def show; end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  protected

  def recipe_params
    params.require(:recipe).permit(:name)
  end

  def load_recipe
    @recipe = current_user.recipes.find(params[:id])
  end

  def after_create_path
    @recipe.persisted? ? edit_recipe_path(@recipe) : recipes_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    redirect_to recipes_path if user_signed_in?
  end

  def create
    @user = User.from_omniauth(request.env['omniauth.auth'].deep_stringify_keys!)
    if @user.persisted?
      sign_in(@user)
    else
      Rails.logger.debug(@user)
      flash[:notice] = 'Something went wrong, please try again.'
    end
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def icon_tag(icon)
    content_tag :span, nil, class: "glyphicon glyphicon-#{icon}"
  end
  
end

app/views/application/_account_settings.html.erb
<div class="modal fade" id="accountSettings">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Account Settings</h4>
      </div>
      <div class="modal-body">
        <%= form_tag '/nothing', class: 'form-two-columns' do %>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-3">
                <label>Email</label>
              </div>
              <div class="col-sm-9">
                <%= text_field_tag 'email', '', class: 'form-control', placeholder: 'Your main email' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary">Save settings</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Recipppe</title>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="sidebar">
      <a href="#" class="btn close">+</a>
      <div class="sidebar-inner">
        <% if user_signed_in? %>
          <ul>
            <li><%= link_to 'Your Profile', recipes_path %></li>
            <li><a href="#">New Recipe</a></li>
            <li><a href="#">Saved Drafts</a></li>
            <li><a href="#">Account Settings</a></li>
          </ul>
        <% end %>
      </div>
    </nav>
    <%= yield %>
    <%= render 'account_settings' if user_signed_in? %>
    <%= javascript_include_tag 'application' %>
    <script>
      window.layout = new Layout();
      window.sidebar = new Sidebar();
    </script>
    <%= yield :bottom %>
  </body>
</html>

app/views/recipes/_new.html.erb
<div class="modal fade" id="newRecipe">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Create a new Recipe</h4>
      </div>
      <%= form_for Recipe.new do |f| %>
        <div class="modal-body">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Type your recipe name' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-default">Create</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="layout">
  <div class="recipe clearfix">
    <div class="header clearfix">
      <div class="header-background" data-background-url="<%= @recipe.cover_image_large_url %>"></div>
      <a href="#" class="btn open-sidebar" title="Menu"></a>

      <div class="cover-upload">
        <div>Drag or <a class="clickable">select</a> a cover photo</div>
        <div class="upload-details"></div>
      </div>
      <div class="inner">
        <%= content_tag :h1, @recipe.name, class: 'recipe-text-field', contenteditable: true, data: { name: 'name' } %>
        <div class="details">
          <%= content_tag :span, '', class: 'recipe-select-field', data: {
            default: @recipe.category.name,
            name: 'category_id',
            resource_url: api_categories_path(format: :json)
          } %> for
          <%= content_tag :span, '', class: 'recipe-select-field', data: {
            default: @recipe.servings,
            name: 'servings',
            resource_content: '2,4,6,8,10'
          } %> people, in
          <%= content_tag :span, '', class: 'recipe-select-field', data: {
            default: @recipe.preparation_time,
            name: 'preparation_time',
            resource_content: '5,10,15,20,30,45,60,120'
          } %> minutes
        </div>
      </div>

    </div>
    <section class="content">
      <div class="inner clearfix"></div>
      <div class="editing-tools">
        <a class="open-tools" data-toggle="dropdown">
          <span>+</span>
          <span class="text">Add item</span></a>
      </div>
    </section>
  </div>
</div>

<div class="modal fade" id="toolsModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <strong>Include</strong>
        <ul class="clearfix">
          <li class="line-item-tool"><a href="#" data-type="single" data-tag="h2"></a></li>
          <li class="line-item-tool"><a href="#" data-type="single" data-tag="p"></a></li>
          <li class="line-item-tool"><a href="#" data-type="list" data-tag="ul"></a></li>
          <li class="line-item-tool"><a href="#" data-type="list" data-tag="ol"></a></li>
          <li class="line-item-tool"><a href="#" data-type="image" data-tag="one"></a></li>
          <li class="sort-tool"><a href="#" data-tag="sort"></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="recipeImagesModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Recipe Gallery</h4>
      </div>
      <div class="recipe-images-upload">
        <div class="modal-body">
          <div class="row">
            <% @recipe.recipe_images.each do |recipe_image| %>
              <div class="col-xs-6 col-md-4">
                <div class="thumbnail" data-id="<%= recipe_image.id %>" data-url="<%= recipe_image.image.url(:large) %>">
                  <%= image_tag recipe_image.image.url(:medium) %>
                  <a href="#" class="delete"><%= icon_tag('trash') %></a>
                </div>
              </div>
            <% end %>
            <div class="col-xs-6 col-md-4">
              <a href="#" class="thumbnail clickable">
                Add Image
              </a>
            </div>
          </div>
          <div class="upload-details hidden"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :bottom do %>
  <script>
    var recipeId = '<%= @recipe.id %>';
    var $defaultTarget = $('.recipe .content .inner');
    editing = new Editing();
    editing.init();
  </script>
<% end %>

app/views/recipes/index.html.erb
<div class="container index">
  <div class="row">
    <div class="col-sm-12">

      <div class="profile">
        <div class="user-image" data-background-url="<%= current_user.large_profile_image %>"></div>
        <h2><%= current_user.name %></h2>
        <div class="actions">
          <%= link_to icon_tag('off'), signout_path %>
        </div>
      </div>

      <div class="row recipe-thumbnails">
        <% @recipes.each do |recipe| %>
          <div class="col-sm-4">
            <div class="thumbnail recipe-thumbnail clearfix">
              <%= link_to edit_recipe_path(recipe), class: 'image-anchor' do %>
                <div class="image" data-background-url="<%= recipe.cover_image.url(:medium) %>"></div>
              <% end %>
              <strong class="clearfix"><%= truncate recipe.name, length: 60 %></strong>
              <div class="pull-left">
                <span><%= icon_tag('tag') %> <%= recipe.category.name %></span>
                <span><%= icon_tag('time') %> <%= recipe.preparation_time %></span>
                <span><%= icon_tag('cutlery') %> <%= recipe.servings %></span>
              </div>
              <div class="pull-right">
                <%= link_to icon_tag('trash'), recipe, method: :delete, class: 'text-danger' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="create">
        <%= link_to '+', '#', class: 'new-recipe' %>
      </div>

    </div>
  </div>
</div>

<%= render 'new' %>

app/views/steps/create.js.erb
<% if @step.persisted? %>
  var newStep = $('<%=j render "recipes/step", step: @step %>');

  <% if params[:after_step] %>
  var afterStep = $('.step[data-id="<%= params[:after_step] %>"]');
  if (afterStep.length) {
    afterStep.after(newStep);
  }
  <% else %>
  $('.steps ul').append(newStep);
  <% end %>

  $(newStep).find('.step-content').focus();
  window.textStep.updatePositions('.steps');
  <% if @step.is_image? %>
  window.upload.setUploadArea('.step[data-id="<%= @step.id %>"] .thumbnail');
  <% end%>
<% end %>

app/views/steps/destroy.js.erb
prevStep = $('.step[data-id=<%= @step.id %>]').prev('.step');
$('.step[data-id=<%= @step.id %>]').remove();
if (prevStep.length) {
  placeCaretAtEnd(prevStep.find('.step-content').get(0))
}

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h2>Recipppe</h2>
      <%= link_to 'Login with Facebook', '/auth/facebook', class: 'btn btn-primary' %>
    </div>
  </div>
</div>